version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/search_admin
      - DIRECT_URL=postgresql://postgres:postgres@db:5432/search_admin
    depends_on:
      - db
    networks:
      - search-box-network
    # Run migrations before starting the app
    command: sh -c "npx prisma migrate deploy && node server.js"

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=search_admin
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - search-box-network

networks:
  search-box-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
